// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearResults() {
  return window['go']['backend']['App']['ClearResults']();
}

export function GetConfig() {
  return window['go']['backend']['App']['GetConfig']();
}

export function GetWorkingProxies() {
  return window['go']['backend']['App']['GetWorkingProxies']();
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function PauseCheck() {
  return window['go']['backend']['App']['PauseCheck']();
}

export function ResumeCheck() {
  return window['go']['backend']['App']['ResumeCheck']();
}

export function StartCheck(arg1) {
  return window['go']['backend']['App']['StartCheck'](arg1);
}

export function StopCheck() {
  return window['go']['backend']['App']['StopCheck']();
}

export function UpdateConfig(arg1) {
  return window['go']['backend']['App']['UpdateConfig'](arg1);
}
