// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {backend} from '../models';

export function ClearResults():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetWorkingProxies():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function PauseCheck():Promise<string>;

export function ResumeCheck():Promise<string>;

export function StartCheck(arg1:backend.CheckParams):Promise<string>;

export function StopCheck():Promise<string>;

export function UpdateConfig(arg1:config.Config):Promise<void>;
