// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function ClearResults():Promise<string>;

export function GetWorkingProxies():Promise<Array<string>>;

export function PauseCheck():Promise<string>;

export function ResumeCheck():Promise<string>;

export function StartCheck(arg1:backend.CheckParams):Promise<string>;

export function StopCheck():Promise<string>;
